export const PATIENT_ROUTES = {
  // Auth / Onboarding
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  CLERK_AUTH: 'CLERK_AUTH',
  PERSONAL_INFO: 'PERSONAL_INFO',
  MEDICAL_HISTORY: 'MEDICAL_HISTORY',
  ONBOARDING_COMPLETE: 'ONBOARDING_COMPLETE',

  // Main Tabs
  HOME: 'HOME',

  // Appointments
  APPOINTMENTS: 'APPOINTMENTS',
  BOOK_APPOINTMENT: 'BOOK_APPOINTMENT',
  APPOINTMENT_DETAIL: 'APPOINTMENT_DETAIL',
  RESCHEDULE: 'RESCHEDULE',

  // Exercises
  EXERCISES: 'EXERCISES',
  EXERCISE_DETAIL: 'EXERCISE_DETAIL',
  EXERCISE_COMPLETE: 'EXERCISE_COMPLETE',

  // Messages
  MESSAGES: 'MESSAGES',
  CHAT: 'CHAT',

  // Progress
  PROGRESS: 'PROGRESS',
  LOG_PAIN: 'LOG_PAIN',

  // Invoices
  INVOICES: 'INVOICES',
  INVOICE_DETAIL: 'INVOICE_DETAIL',

  // Video
  VIDEO_CALL: 'VIDEO_CALL',

  // Profile
  PROFILE: 'PROFILE',
  EDIT_PROFILE: 'EDIT_PROFILE',
  SETTINGS: 'SETTINGS',
};
