export const PATIENT_ROUTES = {
  // Auth / Onboarding
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  CLERK_AUTH: 'CLERK_AUTH',
  PERSONAL_INFO: 'PERSONAL_INFO',
  PAIN_LOCATION: 'PAIN_LOCATION',
  PAIN_SEVERITY: 'PAIN_SEVERITY',
  PAIN_DURATION: 'PAIN_DURATION',
  TREATMENT_HISTORY: 'TREATMENT_HISTORY',
  RECOVERY_GOALS: 'RECOVERY_GOALS',
  AVAILABILITY: 'AVAILABILITY',
  ONBOARDING_COMPLETE: 'ONBOARDING_COMPLETE',

  // Main Tabs
  HOME: 'HOME',
  HOME_SCREEN: 'HOME_SCREEN', // stack-internal name — avoids HOME > HOME nesting warning

  // Appointments
  APPOINTMENTS: 'APPOINTMENTS',
  BOOK_APPOINTMENT: 'BOOK_APPOINTMENT',
  BOOK_THERAPIST: 'BOOK_THERAPIST',
  SLOT_SELECTION: 'SLOT_SELECTION',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  APPOINTMENT_DETAIL: 'APPOINTMENT_DETAIL',
  RESCHEDULE: 'RESCHEDULE',

  // Exercises
  EXERCISES: 'EXERCISES',
  EXERCISE_DETAIL: 'EXERCISE_DETAIL',
  EXERCISE_COMPLETE: 'EXERCISE_COMPLETE',
  SESSION: 'SESSION',

  // Messages
  MESSAGES: 'MESSAGES',
  MESSAGES_SCREEN: 'MESSAGES_SCREEN', // stack-internal name — avoids MESSAGES > MESSAGES nesting warning
  CHAT: 'CHAT',
  CHAT_ROOM: 'CHAT_ROOM',

  // Progress
  PROGRESS: 'PROGRESS',
  LOG_PAIN: 'LOG_PAIN',

  // Invoices
  INVOICES: 'INVOICES',
  INVOICE_DETAIL: 'INVOICE_DETAIL',

  // Video
  VIDEO_CALL: 'VIDEO_CALL',

  // Profile
  PROFILE: 'PROFILE',
  EDIT_PROFILE: 'EDIT_PROFILE',
  SETTINGS: 'SETTINGS',
};
